/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Laura_Duque (https://sketchfab.com/Laura_Duque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-camara-f3fa555e35f9437895b166e366d0b9cf
Title: vintage camara
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const Camera = (props) => {
  const { nodes, materials } = useGLTF('/models/vintage_camara.glb')
  return (
    <Float floatIntensity={1}>
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 7.133, 0]} scale={[4.066, 8.237, 13.948]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube1_standardSurface1_0.geometry}
            material={materials.standardSurface1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube1_lambert4_0.geometry}
            material={materials.lambert4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube1_lambert10_0.geometry}
            material={materials.lambert10}
          />
        </group>
        <group position={[1.151, 6.655, 5.765]} scale={[3.73, 4.756, 3.73]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube2_lambert3_0.geometry}
            material={materials.lambert3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube2_standardSurface1_0.geometry}
            material={materials.standardSurface1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube2_lambert2_0.geometry}
            material={materials.lambert2}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder1_lambert5_0.geometry}
          material={materials.lambert5}
          position={[3.083, 6.719, -0.8]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[2.772, 1.173, 2.772]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder2_standardSurface1_0.geometry}
          material={materials.standardSurface1}
          position={[0, 11.276, 3.481]}
          scale={[0.563, 0.255, 0.563]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_standardSurface1_0.geometry}
          material={materials.standardSurface1}
          position={[0, 11.311, 3.485]}
          scale={0.315}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube3_lambert7_0.geometry}
          material={materials.lambert7}
          position={[-0.218, 4.795, -9.731]}
          rotation={[0.231, 0, 0]}
          scale={[0.73, 8.067, 1.126]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube4_blinn3_0.geometry}
          material={materials.blinn3}
          position={[-0.238, 8.91, -8.712]}
          rotation={[0.38, 0, 0]}
          scale={[1.103, 1, 1]}
        />
        <mesh
          castShadow 
          receiveShadow
          geometry={nodes.pCube5_blinn3_0.geometry}
          material={materials.blinn3}
          position={[-0.31, 10.155, -6.498]}
          rotation={[-1.579, 0, 0]}
          scale={[1.103, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pTorus1_standardSurface1_0.geometry}
          material={materials.standardSurface1}
          position={[-0.228, 9.96, -7.727]}
          rotation={[-0.443, 0, 0]}
          scale={[0.19, 0.261, 0.261]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder4_lambert11_0.geometry}
          material={materials.lambert11}
          position={[4.286, 6.752, -0.824]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[2.853, 0.121, 2.853]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder5_lambert9_0.geometry}
          material={materials.lambert9}
          position={[0, 11.473, -4.532]}
          scale={[1, 0.34, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube6_lambert8_0.geometry}
          material={materials.lambert8}
          position={[1.915, 10.107, -1.239]}
          scale={[0.106, 1.218, 1.883]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube7_blinn2_0.geometry}
          material={materials.blinn2}
          position={[1.893, 10.144, -3.193]}
          scale={[0.107, 1.194, 1.572]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPipe3_lambert6_0.geometry}
          material={materials.lambert6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.typeMesh1_blinn1_0.geometry}
          material={materials.blinn1}
          position={[1.988, 10.596, 5.62]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.029, 0.032, 0.025]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.typeMesh2_blinn4_0.geometry}
          material={materials.blinn4}
          position={[2.008, 10.054, -4.187]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.033}
        />
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('/models/vintage_camara.glb')

export default Camera