/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tirrellclark.75 (https://sketchfab.com/tirrellclark.75)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shyguy-680b1e0cb7b142149012ec7d38f95d43
Title: Shyguy
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const Shyguy = (props) => {
  const { nodes, materials } = useGLTF('/models/shyguy.glb')
  return (
    <Float floatIntensity={1}>
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.shyguy_tex}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
    </Float>
  )
}

useGLTF.preload('/models/shyguy.glb')

export default Shyguy