/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tirrellclark.75 (https://sketchfab.com/tirrellclark.75)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shyguy-680b1e0cb7b142149012ec7d38f95d43
Title: Shyguy
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const Target = (props) => {
  const { nodes, materials } = useGLTF('/models/ath-m50x_headphone.glb')
  return (
    <Float floatIntensity={1}>
    <group {...props} dispose={null}>
      <group position={[2.136, 6.298, 4.684]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[-0.056, 0.047, -0.009]} rotation={[-3.092, -1.517, 1.838]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['8_EarCab001_earCab_0'].geometry}
            material={materials.earCab}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['8_EarCab001_earCabFabric_0'].geometry}
            material={materials.earCabFabric}
          />
        </group>
        <group position={[-0.081, 0.039, 0.009]} rotation={[-3.092, -1.517, 1.838]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['7_EarCover001_Headphone_Default_0'].geometry}
            material={materials.Headphone_Default}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['7_EarCover001_MetalRing_0'].geometry}
            material={materials.MetalRing}
          />
        </group>
        <group position={[-0.101, 0.047, 0.037]} rotation={[Math.PI / 2, 0, -1.354]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['2_X_Connector_Bottom001_Headphone_Default_0'].geometry}
            material={materials.Headphone_Default}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['2_X_Connector_Bottom001_MetalRing_0'].geometry}
            material={materials.MetalRing}
          />
        </group>
        <group position={[-0.021, 0.047, 0.077]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['01_MetalBar001_HeadbarMetalclean_0'].geometry}
            material={materials['HeadbarMetal.clean']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['01_MetalBar001_HeadbarMetal_0'].geometry}
            material={materials.HeadbarMetal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['01_MetalBar001_Headphone_Default_0'].geometry}
            material={materials.Headphone_Default}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['6_EarCoverHole001_Headphone_Default_0'].geometry}
          material={materials.Headphone_Default}
          position={[-0.072, 0.08, -0.011]}
          rotation={[-Math.PI, -1.517, 1.571]}
          scale={1.291}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['4_EarCoverConnector001__0'].geometry}
          material={materials['4_EarCoverConnector.001__0']}
          position={[-0.086, 0.047, 0.005]}
          rotation={[0, -0.485, -Math.PI / 2]}
          scale={[1, 0.745, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5_EarCoverConnectorHolder001_Headphone_Default_0'].geometry}
          material={materials.Headphone_Default}
          position={[-0.077, 0.027, -0.011]}
          rotation={[Math.PI / 2, 0, -1.086]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['3_Logo001_Headphone_Default_0'].geometry}
          material={materials.Headphone_Default}
          position={[-0.094, 0.047, 0.021]}
          rotation={[0, -0.38, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['2_X_Connector_Top001_Headphone_Default_0'].geometry}
          material={materials.Headphone_Default}
          position={[-0.104, 0.047, 0.052]}
          rotation={[0, -0.217, -Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['02_FabricBar001_earCab_0'].geometry}
          material={materials.earCab}
          position={[-0.021, 0.047, 0.077]}
          scale={[1, 1.869, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['02_BarEnd001_Headphone_Default_0'].geometry}
          material={materials.Headphone_Default}
          position={[-0.099, 0.047, 0.113]}
          rotation={[0, 0.346, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['02_Screws003_Screw_0'].geometry}
          material={materials.Screw}
          position={[-0.096, 0.036, 0.112]}
          rotation={[3.134, 1.212, -1.564]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['02_Screws004_Screw_0'].geometry}
          material={materials.Screw}
          position={[-0.096, 0.057, 0.112]}
          rotation={[3.134, 1.212, -1.564]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['02_Screws005_Screw_0'].geometry}
          material={materials.Screw}
          position={[-0.1, 0.035, 0.063]}
          rotation={[0.178, 1.556, 1.393]}
          scale={0.593}
        />
      </group>
    </group>
    </Float>
  )
}

useGLTF.preload('/models/ath-m50x_headphone.glb')

export default Target

